### ISSUE TITLE
TypeError: Object #<ReadStream> has no method 'isPaused'

### ISSUE THREAD

**Issue by meetar** [polygon-city/citygml-to-obj#7]
Attempting to run a test immediately returns an error:

```
/cityGMLtest/node_modules/citygml-to-obj/index.js:82
      if (processQueue.length < maxQueue && readStream.isPaused()) {
                                                       ^
TypeError: Object #<ReadStream> has no method 'isPaused'
    at /cityGMLtest/node_modules/citygml-to-obj/index.js:82:56
    at /cityGMLtest/node_modules/citygml-to-obj/node_modules/lodash/index.js:3073:15
    at baseForOwn (/cityGMLtest/node_modules/citygml-to-obj/node_modules/lodash/index.js:2046:14)
    at /cityGMLtest/node_modules/citygml-to-obj/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/cityGMLtest/node_modules/citygml-to-obj/node_modules/lodash/index.js:3346:13)
    at processWorkers (/cityGMLtest/node_modules/citygml-to-obj/index.js:70:5)
    at updateQueue (/cityGMLtest/node_modules/citygml-to-obj/index.js:65:3)
    at wrapper [as _onTimeout] (timers.js:258:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by robhawkes** [comment]
Hmm. What version of Node are you using (`node -v`)? I'm using `v0.12.6` which might make a difference as I know streams are changing a lot.

**Comment by meetar** [comment]
yep – it was 0.10, updating fixes this
